version: '3.8'
services:
  frontend:
    build:
      context: ./deploy
      dockerfile: Dockerfile
    ports:
      - '5008:80'
      - '443:443'
    volumes:
      - .:/var/www/html
      - ./deploy/default.conf:/etc/nginx/sites-available/default